#Made by xIdentified
debug_mode: false

api_key: "YOUR_OPENAI_API_KEY"
chatgpt_engine: "gpt-3.5-turbo-1106" # The OpenAI GPT engine to use
max_response_length: 200 # Maximum length of response from ChatGPT (in tokens)
max_api_calls_per_second: 5

# Time (in milliseconds) before the conversation times out
response_timeout: 60000
# Minimum characters in outgoing player message
min_char_length: 10
# Cooldown duration in milliseconds (e.g., 3000 milliseconds = 3 seconds)
chat_cooldown: 3000

# The default prompt your ChatGPT responses will be based off of. What's set here should apply to all NPCs.
# Useful for setting base rules like, "don't stray off-topic" or "you are an NPC in Minecraft"
default_prompt: "You are an NPC in Minecraft: "

# Replace 'npc_name' with the name of the NPC (as used in Citizens) and place your prompt in quotes.
npcs:
  npc_name: "This is an example prompt for the NPC."

# Gives your NPCs more accurate context to their location in the world, I recommend at least adding spawn
points_of_interest:
  world:
    Spawn: "0,64,0"
    Mine: "200,64,50"
    Village: "150,70,150"
  world_nether:
    Castle: "75,80,-100"

# You can name colors using default codes like "&6" or any valid hex color like "#FFAA00"
chat_colors:
  npc_name: "#37B5FC"
  player_name: "&a"
  npc_message: "&7"
  player_message: "&f"

# Optionally split NPC responses, so they don't send as paragraphs
split_long_messages: false

# Popup dialogue that prompts player to begin conversation. Leave empty to disable.
conversation_start_popup: "Right-click to talk"
# Phrase to end conversations with, required.
conversation_end_phrase: "cancel"
# Number of days NPCs will remember past dialogue
npc_memory_duration: 7

storage:
  type: 'sqlite' # Options: sqlite, mysql
  mysql:
    host: 'localhost'
    port: 3306
    database: 'archgpt'
    username: 'root'
    password: 'password'

translation:
  use-player-client-locale: true  # Use player locale for plugin messages and ChatGPT response language
  default-locale: "en" # For plugin messages
  libre_endpoint: 'https://libretranslate.de' # For ChatGPT responses