# Made by xIdentified - https://discord.gg/emDFbsKNV4
# To edit chat colors, go to lang/styles.yml

debug_mode: false

api_key: "YOUR_OPENAI_API_KEY"
chatgpt_engine: "gpt-3.5-turbo-1106" # The OpenAI GPT engine to use
max_response_length: 150 # Maximum length of response from ChatGPT (in tokens)
max_api_calls_per_second: 5

# Time (in milliseconds) before the conversation times out
response_timeout: 60000
# Minimum characters in outgoing player message
min_char_length: 10
# Cooldown duration in milliseconds (e.g., 3000 milliseconds = 3 seconds)
chat_cooldown: 3000

# The default prompt your ChatGPT responses will be based off of. What's set here will apply to all NPCs.
# Useful for setting context like, "this server has custom enchantments" or "you can claim land by xyz"
# Be mindful of how long this is, as it will be sent to the API each time.
default_prompt: "You live in a server called CarrotCraft. You like to eat carrots. Mmm, carrots."

# Replace 'npc_name' with the name of the NPC (as used in Citizens) and place your prompt in quotes.
npcs:
  npc_name: "This is an example prompt for the NPC."

# Gives your NPCs more accurate context to their location in the world, I recommend adding landmarks like
# spawn, towns, any places you want players to go like a public mine, dungeons, etc.
points_of_interest:
  world:
    Spawn: "0,64,0"
    Mine: "200,64,50"
    Village: "150,70,150"
  world_nether:
    Castle: "75,80,-100"

# Optionally split NPC responses, so they don't send as paragraphs
split_long_messages: false
# Popup dialogue that prompts player to begin conversation. Leave empty to disable.
conversation_start_popup: "Right-click to talk"
# Phrase to end conversations with.
conversation_end_phrase: "cancel"
# Time (in Minecraft days) NPCs will remember conversations. Format: 1d, 1w, 1m etc.
npc_memory_duration: 7d

storage:
  type: 'sqlite' # Options: sqlite, mysql
  mysql:
    host: 'localhost'
    port: 3306
    database: 'archgpt'
    username: 'root'
    password: 'password'

translation:
  use-player-client-locale: true  # Use player locale for plugin messages and ChatGPT response language
  default-locale: "en" # For plugin messages
  libre_endpoint: 'https://libretranslate.de' # For ChatGPT responses
