name: ArchGPT
author: xIdentified
version: '${project.version}'
main: me.xidentified.archgpt.ArchGPT
api-version: '1.20'

depend: [Citizens]
softdepend: [PlaceholderAPI, MMOCore]

libraries:
  - net.kyori:adventure-api:4.14.0
  - net.kyori:adventure-platform-bukkit:4.3.1
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-text-serializer-legacy:4.14.0
  - net.kyori:adventure-text-serializer-gson:4.14.0
  - net.kyori:adventure-text-serializer-plain:4.14.0

commands:
  archgpt:
    description: Main command for the plugin
    usage: /<command> [broadcast|version|reload|reset-npc-memory|clear-all-conversations|setnpc|debug]
    permission: archgpt.admin
  npcreports:
    description: Manage and view NPC message reports.
    usage: /<command>
  reportnpcmessage:
    description: Reports an NPC message
    usage: /<command>
  selectreporttype:
    description: Select a type for the report.
    usage: /<command> <type>

permissions:
  archgpt.admin:
    description: Access to admin commands
    default: op